name: scheduled-tests
on: [push]
env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: saucelabs/saucectl-run-action@v1
        with:
          testing-environment: ""
          concurrency: 10
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npx wdio run wdio.conf.js
