name: scheduled-tests

on:
  push:
    branch:
      - "**"
  schedule:
    - cron: '00 10 * * 1'
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
    
    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs

      - uses: saucelabs/saucectl-run-action@v1
        with:
          testing-environment: ""
          concurrency: 10    
  
      - run: npx wdio run wdio.conf.js
      
      - name: Collect build data
        if: always()
        run: expr $(date +%s) - ${START_TIME}
        
