apiVersion: v1alpha
kind: puppeteer
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 2
  sauceignore: .sauceignore
suites:
- name: puppeteer - docker - chrome
  browser: chrome
puppeteer:
  version: 10.1.0
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
